#!/usr/bin/env bash

# Variáveis de cor
CYANO='\033[0;36m'
VERMELHO='\033[0;31m'
FIM='\033[m'

# CTRL + C/Z para fechar o programa
trap encerr 2

encerr(){
  echo -e "\n${VERMELHO}Saindo...${FIM}\n"
  # Exit status de 'processo interrompido'
  exit 130
}

# -u OU -url no parâmetro inicial startando o script
if [[ "$1" == "-u" ]] || [[ "$1" == "-url" ]]; then
  while true; do
    echo -e "\n+${CYANO} Digite uma URL${FIM} (digite 'quit OU q' para sair)"
    read -rp "$(echo -e $CYANO"  URL: "$FIM)" URL_
    
    # Regex com ancora ^ ou $ para delimitar o fim/início da regex (ou as duas)
    # Se $URL_ for == quit em letra maiúscula em um.. dois.. ou todos os dígitos...
    if [[ "$URL_" =~ ^[Qq][Uu][Ii][Tt]$ ]] || [[ "$URL_" =~ ^[Qq]$ ]]; then
      echo -e "\n${VERMELHO}Saindo...${FIM}\n"
      exit 0
    fi
    echo -e "${CYANO}+ URL encurtada:${FIM} " | curl -s -k "https://is.gd/create.php?format=simple&url=$URL_"
  done

# Senão, todos os parâmetros forem vazios...
elif [[ -z "$*" ]]; then
  echo -e "Uso:\n$0 -u | -url <URL>   :: Encurtar uma URL\n"
  exit 0
else
  # Se o parâmetro 1 não for -u ou -url...
  echo -e "\n${VERMELHO}Parametro desconhecido\nUse:${FIM} $0 ${VERMELHO}para ver o painel de ajuda\nSaindo...\n${FIM}"
  false
fi
