#!/usr/bin/env bash

CYANO='\033[0;36m'
VERMELHO='\033[0;31m'
FIM='\033[m'

if [[ "$1" == "-u" ]] || [[ "$1" == "-url" ]]; then
  while true; do
    echo -e "+${CYANO} Digite uma URL${FIM} (digite 'quit OU q' para sair)"
    read -rp "${CYANO}  URL: ${FIM}" URL_
    
    # Regex com ancora ^ ou $ para delimitar o fim/início da regex (ou as duas)
    # Se $URL_ for == quit em letra maiúscula em um.. dois.. ou todos os dígitos...
    if [[ "$URL_" =~ ^[Qq][Uu][Ii][Tt]$ ]] || [[ "$URL_" =~ ^[Qq]$ ]]; then
      echo -e "\n${VERMELHO}Saindo...${FIM}\n"
      exit 0
    fi
    echo -e "+ URL encurtada: " | curl -s -k "https://is.gd/create.php?format=simple&url=$URL_"
    echo -e "${FIM}"
  done
elif [[ -z "$*" ]]; then
  echo -e "Uso:\n$0 -u | -url <URL>   :: Encurtar uma URL\n"
  exit 0
else
  false
fi
